/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/spaceship.glb -o src/components/Spaceship.jsx 
*/

import React, { forwardRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("public/Models/Spaceship.glb");
  useFrame((_state, delta) => {
    if (ref?.current) {
      ref.current.rotation.y += 0.2 * delta; // optional rotation
    }
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Spaceship_1.geometry}
          material={materials.White}
        />
        <mesh
          geometry={nodes.Spaceship_2.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
});
export default Model;

useGLTF.preload("public/Models/Spaceship.glb");
